2024-09-27T11:00:36.094327+00:00 app[web.1]: ^^^^^^^^^^^^^^^
2024-09-27T11:00:36.094327+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
2024-09-27T11:00:36.094328+00:00 app[web.1]: self.callable = self.load()
2024-09-27T11:00:36.094328+00:00 app[web.1]: ^^^^^^^^^^^
2024-09-27T11:00:36.094328+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
2024-09-27T11:00:36.094328+00:00 app[web.1]: return self.load_wsgiapp()
2024-09-27T11:00:36.094328+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^
2024-09-27T11:00:36.094329+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
2024-09-27T11:00:36.094329+00:00 app[web.1]: return util.import_app(self.app_uri)
2024-09-27T11:00:36.094329+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T11:00:36.094329+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
2024-09-27T11:00:36.094329+00:00 app[web.1]: mod = importlib.import_module(module)
2024-09-27T11:00:36.094330+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T11:00:36.094332+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-09-27T11:00:36.094334+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2024-09-27T11:00:36.094334+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T11:00:36.094335+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-09-27T11:00:36.094335+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-09-27T11:00:36.094336+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-09-27T11:00:36.094336+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-09-27T11:00:36.094336+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024-09-27T11:00:36.094336+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-09-27T11:00:36.094336+00:00 app[web.1]: File "/app/app/run.py", line 6, in <module>
2024-09-27T11:00:36.094336+00:00 app[web.1]: from nltk.stem import WordNetLemmatizer
2024-09-27T11:00:36.094336+00:00 app[web.1]: ModuleNotFoundError: No module named 'nltk'
2024-09-27T11:00:36.094391+00:00 app[web.1]: [2024-09-27 11:00:36 +0000] [9] [INFO] Worker exiting (pid: 9)
2024-09-27T11:00:36.094440+00:00 app[web.1]: [2024-09-27 11:00:36 +0000] [17] [ERROR] Exception in worker process
2024-09-27T11:00:36.094440+00:00 app[web.1]: Traceback (most recent call last):
2024-09-27T11:00:36.094441+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
2024-09-27T11:00:36.094441+00:00 app[web.1]: worker.init_process()
2024-09-27T11:00:36.094441+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
2024-09-27T11:00:36.094441+00:00 app[web.1]: self.load_wsgi()
2024-09-27T11:00:36.094441+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
2024-09-27T11:00:36.094441+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2024-09-27T11:00:36.094441+00:00 app[web.1]: ^^^^^^^^^^^^^^^
2024-09-27T11:00:36.094442+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
2024-09-27T11:00:36.094442+00:00 app[web.1]: self.callable = self.load()
2024-09-27T11:00:36.094442+00:00 app[web.1]: ^^^^^^^^^^^
2024-09-27T11:00:36.094442+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
2024-09-27T11:00:36.094442+00:00 app[web.1]: return self.load_wsgiapp()
2024-09-27T11:00:36.094442+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^
2024-09-27T11:00:36.094442+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
2024-09-27T11:00:36.094442+00:00 app[web.1]: return util.import_app(self.app_uri)
2024-09-27T11:00:36.094442+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T11:00:36.094443+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
2024-09-27T11:00:36.094443+00:00 app[web.1]: mod = importlib.import_module(module)
2024-09-27T11:00:36.094443+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T11:00:36.094443+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-09-27T11:00:36.094443+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2024-09-27T11:00:36.094443+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T11:00:36.094443+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-09-27T11:00:36.094443+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-09-27T11:00:36.094443+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-09-27T11:00:36.094444+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-09-27T11:00:36.094444+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024-09-27T11:00:36.094444+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-09-27T11:00:36.094444+00:00 app[web.1]: File "/app/app/run.py", line 6, in <module>
2024-09-27T11:00:36.094444+00:00 app[web.1]: from nltk.stem import WordNetLemmatizer
2024-09-27T11:00:36.094444+00:00 app[web.1]: ModuleNotFoundError: No module named 'nltk'
2024-09-27T11:00:36.094547+00:00 app[web.1]: [2024-09-27 11:00:36 +0000] [17] [INFO] Worker exiting (pid: 17)
2024-09-27T11:00:36.155411+00:00 app[web.1]: [2024-09-27 11:00:36 +0000] [2] [ERROR] Worker (pid:9) exited with code 3
2024-09-27T11:00:36.156426+00:00 app[web.1]: [2024-09-27 11:00:36 +0000] [2] [ERROR] Worker (pid:17) exited with code 3
2024-09-27T11:00:36.156493+00:00 app[web.1]: Traceback (most recent call last):
2024-09-27T11:00:36.156504+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 208, in run
2024-09-27T11:00:36.156695+00:00 app[web.1]: self.sleep()
2024-09-27T11:00:36.156742+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 359, in sleep
2024-09-27T11:00:36.156852+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2024-09-27T11:00:36.156945+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-27T11:00:36.156955+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
2024-09-27T11:00:36.157013+00:00 app[web.1]: self.reap_workers()
2024-09-27T11:00:36.157030+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 529, in reap_workers
2024-09-27T11:00:36.157116+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2024-09-27T11:00:36.157145+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2024-09-27T11:00:36.157146+00:00 app[web.1]: 
2024-09-27T11:00:36.157148+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2024-09-27T11:00:36.157156+00:00 app[web.1]: 
2024-09-27T11:00:36.157156+00:00 app[web.1]: Traceback (most recent call last):
2024-09-27T11:00:36.157164+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2024-09-27T11:00:36.157195+00:00 app[web.1]: sys.exit(run())
2024-09-27T11:00:36.157225+00:00 app[web.1]: ^^^^^
2024-09-27T11:00:36.157225+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 66, in run
2024-09-27T11:00:36.157289+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
2024-09-27T11:00:36.157314+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/base.py", line 235, in run
2024-09-27T11:00:36.157369+00:00 app[web.1]: super().run()
2024-09-27T11:00:36.157385+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/base.py", line 71, in run
2024-09-27T11:00:36.157418+00:00 app[web.1]: Arbiter(self).run()
2024-09-27T11:00:36.157435+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 228, in run
2024-09-27T11:00:36.157484+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2024-09-27T11:00:36.157507+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 341, in halt
2024-09-27T11:00:36.157580+00:00 app[web.1]: self.stop()
2024-09-27T11:00:36.157602+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 395, in stop
2024-09-27T11:00:36.157703+00:00 app[web.1]: time.sleep(0.1)
2024-09-27T11:00:36.157738+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
2024-09-27T11:00:36.157815+00:00 app[web.1]: self.reap_workers()
2024-09-27T11:00:36.157835+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 529, in reap_workers
2024-09-27T11:00:36.157947+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2024-09-27T11:00:36.157970+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2024-09-27T11:00:36.222351+00:00 heroku[web.1]: Process exited with status 1
2024-09-27T11:00:36.254703+00:00 heroku[web.1]: State changed from up to crashed
2024-09-27T11:01:54.428753+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=disaster-response-app-be215b66c206.herokuapp.com request_id=99972c91-9c15-4bfb-b6d9-d32bc9987cf6 fwd="80.142.214.23" dyno= connect= service= status=503 bytes= protocol=https
